---
- type: mastodon
  name: Mastodon
  label: '@neet@mastodon.social'
  url: https://mastodon.social/@neet
  bgColor: '#297ccd'
  fgColor: white
  suggested: true

- type: discord
  name: Discord
  label: '@thegodofneet'
  copyable: thegodofneet
  bgColor: '#7289da'
  fgColor: white
  suggested: true

- type: telegram
  name: Telegram
  label: '@rigarashi'
  url: https://t.me/rigarashi
  bgColor: '#2ca5e0'
  fgColor: white
  suggested: true

- type: keybase
  name: Keybase
  label: '@neet'
  url: https://keybase.io/neet
  bgColor: '#FF6300'
  fgColor: white
  suggested: true

- type: email
  name: Email
  label: n33t5hin@gmail.com
  url: mailto:n33t5hin@gmail.com
  bgColor: '#1981e0'
  fgColor: white

- type: github
  name: GitHub
  label: '@neet'
  url: https://github.com/neet
  bgColor: black
  fgColor: white

- type: gitlab
  name: GitLab.com
  label: '@neetshin'
  url: https://gitlab.com/neetshin
  bgColor: '#de3a25'
  fgColor: white

- type: twitter
  name: X
  label: '@TheGodOfNeet'
  url: https://x.com/thegodofneet
  bgColor: '#1a97f0'
  fgColor: white

- type: twitter
  name: X (NSFW)
  label: '@FlawOfEduaction'
  url: https://x.com/flawofeducation
  bgColor: '#1a97f0'
  fgColor: white

- type: instagram
  name: Instagram
  label: '@TheGodOfNeet'
  url: https://www.instagram.com/thegodofneet/
  bgColor: '#E4405F'
  fgColor: white

- type: line
  name: LINE
  label: thegodofneet
  url: http://line.naver.jp/ti/p/hCtcmGHPxY
  bgColor: '#00B900'
  fgColor: white

- type: medium
  name: Medium
  label: '@neetshin'
  url: https://medium.com/@neetshin
  bgColor: white
  fgColor: black

- type: slideshare
  name: SlideShare
  label: ssuser881c4e
  url: https://www.slideshare.net/ssuser881c4e
  bgColor: '#0077b5'
  fgColor: white

- type: npm
  name: npm
  label: neetshin
  url: https://www.npmjs.com/~neetshin
  bgColor: '#cb3837'
  fgColor: white

- type: docker
  name: DockerHub
  label: neetshin
  url: https://hub.docker.com/r/neetshin/
  bgColor: '#1488c6'
  fgColor: white

- type: bitcoin
  name: Bitcoin
  label: 3AucsLDnY37qipYngLM5KH9heWkJ1AEArv
  copyable: 3AucsLDnY37qipYngLM5KH9heWkJ1AEArv
  bgColor: '#ff8e02'
  fgColor: white

- type: patreon
  name: Patreon
  label: neetshin
  url: https://www.patreon.com/neetshin
  bgColor: '#f96854'
  fgColor: white
