import {
  faBitcoin,
  faDiscord,
  faDocker,
  faGithub,
  faGitlab,
  faInstagram,
  faKeybase,
  faLine,
  faMastodon,
  faMediumM,
  faNpm,
  faPatreon,
  faSlideshare,
  faTelegramPlane,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';

export const faIconMap = {
  mastodon: faMastodon,
  email: faEnvelope,
  discord: faDiscord,
  telegram: faTelegramPlane,
  keybase: faKeybase,
  twitter: faTwitter,
  github: faGithub,
  gitlab: faGitlab,
  medium: faMediumM,
  slideshare: faSlideshare,
  npm: faNpm,
  docker: faDocker,
  bitcoin: faBitcoin,
  patreon: faPatreon,
  instagram: faInstagram,
  line: faLine,
};
