import {
  faBitcoin,
  faDiscord,
  faDocker,
  faGithub,
  faGitlab,
  faInstagram,
  faKeybase,
  faLine,
  faMastodon,
  faMediumM,
  faNpm,
  faPatreon,
  faPython,
  faRust,
  faSlideshare,
  faTelegramPlane,
  faXTwitter,
  IconDefinition,
} from "@fortawesome/free-brands-svg-icons";
import { faEnvelope, faFaceSmileBeam } from "@fortawesome/free-solid-svg-icons";

export const faIconMap: Record<string, IconDefinition | undefined> = {
  mastodon: faMastodon,
  email: faEnvelope,
  discord: faDiscord,
  telegram: faTelegramPlane,
  keybase: faKeybase,
  huggingface: faFaceSmileBeam,
  twitter: faXTwitter,
  github: faGithub,
  gitlab: faGitlab,
  medium: faMediumM,
  slideshare: faSlideshare,
  npm: faNpm,
  docker: faDocker,
  bitcoin: faBitcoin,
  patreon: faPatreon,
  instagram: faInstagram,
  crates: faRust,
  pypi: faPython,
  line: faLine,
};
